CREATE TABLE IF NOT EXISTS Users
(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Handle VARCHAR(255) UNIQUE,
Password VARCHAR(255) NOT NULL,
LastName VARCHAR(255) NOT NULL,
FirstName VARCHAR(255) NOT NULL,
Location VARCHAR(255) NOT NULL
)

CREATE TABLE IF NOT EXISTS Fleets
(
Fleet_ID INT NOT NULL AUTO_INCREMENT,
User_ID INT NOT NULL,
Fleet VARCHAR(155),
PRIMARY KEY(Fleet_ID),
FOREIGN KEY(User_ID) REFERENCES Users(ID)
)

CREATE TABLE IF NOT EXISTS Following
(
User_ID INT NOT NULL,
Following_ID INT NOT NULL,
FOREIGN KEY(User_ID) REFERENCES Users(ID),
FOREIGN KEY(Following_ID) REFERENCES Users(ID),
PRIMARY KEY(User_ID, Following_ID)
)
